name: Laravel

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    env:
      APP_URL: "http://127.0.0.1:8000"
      DB_CONNECTION: sqlite
      DB_DATABASE: database.sqlite
      QUEUE_CONNECTION: sync
    services:
      selenium:
        image: selenium/standalone-chrome

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: actions/checkout@v4
      - run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - run: npm install
      - run: npm run build
      - run: php artisan key:generate
      - run: php artisan migrate --force --no-interaction
      - run: php artisan test
      - run: php artisan dusk:chrome-driver
      - run: ./vendor/laravel/dusk/bin/chromedriver-linux &
      - run: php artisan serve --no-reload &
      - run: php artisan dusk
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: tests/Browser/screenshots/
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: logs
          path: storage/logs/
